### ISSUE TITLE
repair for docs

### ISSUE THREAD

**Issue by mflatt** [zenspider/check-sexp-equal#2]
The documentation doesn't render the module name as intended because `@defmodule[...]` comes before `@title{...}` in "check-sexp-equal.scrbl". Swapping those two fixes the problem.

It's possible that using `defmodule` before `title` should be allowed --- I'll have to think about that more --- but changing the document makes it render correctly with the current release.

**Comment by zenspider** [comment]
Fixed. Thanks!
